version: '3.8'

services:
  disbot:
    image: haokaiii/disbot:latest
    # or if building locally:
    # build: .
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - ./data:/app/data_backup
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"